### PR TITLE
Added common linters

### PR DESCRIPTION
**Pull request by ahcorde**
Added common linters.

I added the License Apache version 2 to this package, Tango icons are Public Domain. I dont' know if this is compatible.

@tfoote 

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by brawner** [comment]
What would you be copyrighting with the Apache license?

**Comment by ahcorde** [comment]
I mean to the package itself

**Comment by dirk-thomas** [comment]
Having the Apache license file but stating a different license in the XML is confusing. Please check other packages which contain external code how to clarify which part is licensed how.

**Comment by ahcorde** [comment]
Fixed, I checked with other packages like `spdlog_vendor` and `console_bridge_vendor`

**Pull request merged**
